/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StudentService } from "../student.service";
import { StudentCreateInput } from "./StudentCreateInput";
import { Student } from "./Student";
import { StudentFindManyArgs } from "./StudentFindManyArgs";
import { StudentWhereUniqueInput } from "./StudentWhereUniqueInput";
import { StudentUpdateInput } from "./StudentUpdateInput";
import { ExamFindManyArgs } from "../../exam/base/ExamFindManyArgs";
import { Exam } from "../../exam/base/Exam";
import { ExamWhereUniqueInput } from "../../exam/base/ExamWhereUniqueInput";
import { PerformanceAnalyticsFindManyArgs } from "../../performanceAnalytics/base/PerformanceAnalyticsFindManyArgs";
import { PerformanceAnalytics } from "../../performanceAnalytics/base/PerformanceAnalytics";
import { PerformanceAnalyticsWhereUniqueInput } from "../../performanceAnalytics/base/PerformanceAnalyticsWhereUniqueInput";
import { QuizFindManyArgs } from "../../quiz/base/QuizFindManyArgs";
import { Quiz } from "../../quiz/base/Quiz";
import { QuizWhereUniqueInput } from "../../quiz/base/QuizWhereUniqueInput";

export class StudentControllerBase {
  constructor(protected readonly service: StudentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Student })
  async createStudent(
    @common.Body() data: StudentCreateInput
  ): Promise<Student> {
    return await this.service.createStudent({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        virtualIdCard: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Student] })
  @ApiNestedQuery(StudentFindManyArgs)
  async students(@common.Req() request: Request): Promise<Student[]> {
    const args = plainToClass(StudentFindManyArgs, request.query);
    return this.service.students({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        virtualIdCard: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Student })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async student(
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<Student | null> {
    const result = await this.service.student({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        virtualIdCard: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Student })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStudent(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() data: StudentUpdateInput
  ): Promise<Student | null> {
    try {
      return await this.service.updateStudent({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          virtualIdCard: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Student })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStudent(
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<Student | null> {
    try {
      return await this.service.deleteStudent({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          virtualIdCard: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/exams")
  @ApiNestedQuery(ExamFindManyArgs)
  async findExams(
    @common.Req() request: Request,
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<Exam[]> {
    const query = plainToClass(ExamFindManyArgs, request.query);
    const results = await this.service.findExams(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        id: true,

        result: {
          select: {
            id: true,
          },
        },

        student: {
          select: {
            id: true,
          },
        },

        subject: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/exams")
  async connectExams(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ExamWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exams: {
        connect: body,
      },
    };
    await this.service.updateStudent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/exams")
  async updateExams(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ExamWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exams: {
        set: body,
      },
    };
    await this.service.updateStudent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/exams")
  async disconnectExams(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: ExamWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exams: {
        disconnect: body,
      },
    };
    await this.service.updateStudent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/performanceAnalyticsItems")
  @ApiNestedQuery(PerformanceAnalyticsFindManyArgs)
  async findPerformanceAnalyticsItems(
    @common.Req() request: Request,
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<PerformanceAnalytics[]> {
    const query = plainToClass(PerformanceAnalyticsFindManyArgs, request.query);
    const results = await this.service.findPerformanceAnalyticsItems(
      params.id,
      {
        ...query,
        select: {
          createdAt: true,
          date: true,
          grade: true,
          id: true,

          student: {
            select: {
              id: true,
            },
          },

          subject: true,
          updatedAt: true,
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/performanceAnalyticsItems")
  async connectPerformanceAnalyticsItems(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: PerformanceAnalyticsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      performanceAnalyticsItems: {
        connect: body,
      },
    };
    await this.service.updateStudent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/performanceAnalyticsItems")
  async updatePerformanceAnalyticsItems(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: PerformanceAnalyticsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      performanceAnalyticsItems: {
        set: body,
      },
    };
    await this.service.updateStudent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/performanceAnalyticsItems")
  async disconnectPerformanceAnalyticsItems(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: PerformanceAnalyticsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      performanceAnalyticsItems: {
        disconnect: body,
      },
    };
    await this.service.updateStudent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/quizzes")
  @ApiNestedQuery(QuizFindManyArgs)
  async findQuizzes(
    @common.Req() request: Request,
    @common.Param() params: StudentWhereUniqueInput
  ): Promise<Quiz[]> {
    const query = plainToClass(QuizFindManyArgs, request.query);
    const results = await this.service.findQuizzes(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        id: true,

        result: {
          select: {
            id: true,
          },
        },

        student: {
          select: {
            id: true,
          },
        },

        subject: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/quizzes")
  async connectQuizzes(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: QuizWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      quizzes: {
        connect: body,
      },
    };
    await this.service.updateStudent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/quizzes")
  async updateQuizzes(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: QuizWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      quizzes: {
        set: body,
      },
    };
    await this.service.updateStudent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/quizzes")
  async disconnectQuizzes(
    @common.Param() params: StudentWhereUniqueInput,
    @common.Body() body: QuizWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      quizzes: {
        disconnect: body,
      },
    };
    await this.service.updateStudent({
      where: params,
      data,
      select: { id: true },
    });
  }
}
