/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ExamCreateNestedManyWithoutStudentsInput } from "./ExamCreateNestedManyWithoutStudentsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { PerformanceAnalyticsCreateNestedManyWithoutStudentsInput } from "./PerformanceAnalyticsCreateNestedManyWithoutStudentsInput";
import { QuizCreateNestedManyWithoutStudentsInput } from "./QuizCreateNestedManyWithoutStudentsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class StudentCreateInput {
  @ApiProperty({
    required: false,
    type: () => ExamCreateNestedManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => ExamCreateNestedManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => ExamCreateNestedManyWithoutStudentsInput, {
    nullable: true,
  })
  exams?: ExamCreateNestedManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => PerformanceAnalyticsCreateNestedManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => PerformanceAnalyticsCreateNestedManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => PerformanceAnalyticsCreateNestedManyWithoutStudentsInput, {
    nullable: true,
  })
  performanceAnalyticsItems?: PerformanceAnalyticsCreateNestedManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => QuizCreateNestedManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => QuizCreateNestedManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => QuizCreateNestedManyWithoutStudentsInput, {
    nullable: true,
  })
  quizzes?: QuizCreateNestedManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  virtualIdCard?: string | null;
}

export { StudentCreateInput as StudentCreateInput };
