/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ExamListRelationFilter } from "../../exam/base/ExamListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { PerformanceAnalyticsListRelationFilter } from "../../performanceAnalytics/base/PerformanceAnalyticsListRelationFilter";
import { QuizListRelationFilter } from "../../quiz/base/QuizListRelationFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";

@InputType()
class StudentWhereInput {
  @ApiProperty({
    required: false,
    type: () => ExamListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExamListRelationFilter)
  @IsOptional()
  @Field(() => ExamListRelationFilter, {
    nullable: true,
  })
  exams?: ExamListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PerformanceAnalyticsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PerformanceAnalyticsListRelationFilter)
  @IsOptional()
  @Field(() => PerformanceAnalyticsListRelationFilter, {
    nullable: true,
  })
  performanceAnalyticsItems?: PerformanceAnalyticsListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => QuizListRelationFilter,
  })
  @ValidateNested()
  @Type(() => QuizListRelationFilter)
  @IsOptional()
  @Field(() => QuizListRelationFilter, {
    nullable: true,
  })
  quizzes?: QuizListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  virtualIdCard?: StringNullableFilter;
}

export { StudentWhereInput as StudentWhereInput };
