/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ExamUpdateManyWithoutStudentsInput } from "./ExamUpdateManyWithoutStudentsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { PerformanceAnalyticsUpdateManyWithoutStudentsInput } from "./PerformanceAnalyticsUpdateManyWithoutStudentsInput";
import { QuizUpdateManyWithoutStudentsInput } from "./QuizUpdateManyWithoutStudentsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class StudentUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ExamUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => ExamUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => ExamUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  exams?: ExamUpdateManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => PerformanceAnalyticsUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => PerformanceAnalyticsUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => PerformanceAnalyticsUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  performanceAnalyticsItems?: PerformanceAnalyticsUpdateManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => QuizUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => QuizUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => QuizUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  quizzes?: QuizUpdateManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  virtualIdCard?: string | null;
}

export { StudentUpdateInput as StudentUpdateInput };
