/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ResourceLibrary as PrismaResourceLibrary,
} from "@prisma/client";

export class ResourceLibraryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ResourceLibraryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.resourceLibrary.count(args);
  }

  async resourceLibraries<T extends Prisma.ResourceLibraryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ResourceLibraryFindManyArgs>
  ): Promise<PrismaResourceLibrary[]> {
    return this.prisma.resourceLibrary.findMany<Prisma.ResourceLibraryFindManyArgs>(
      args
    );
  }
  async resourceLibrary<T extends Prisma.ResourceLibraryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ResourceLibraryFindUniqueArgs>
  ): Promise<PrismaResourceLibrary | null> {
    return this.prisma.resourceLibrary.findUnique(args);
  }
  async createResourceLibrary<T extends Prisma.ResourceLibraryCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ResourceLibraryCreateArgs>
  ): Promise<PrismaResourceLibrary> {
    return this.prisma.resourceLibrary.create<T>(args);
  }
  async updateResourceLibrary<T extends Prisma.ResourceLibraryUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ResourceLibraryUpdateArgs>
  ): Promise<PrismaResourceLibrary> {
    return this.prisma.resourceLibrary.update<T>(args);
  }
  async deleteResourceLibrary<T extends Prisma.ResourceLibraryDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ResourceLibraryDeleteArgs>
  ): Promise<PrismaResourceLibrary> {
    return this.prisma.resourceLibrary.delete(args);
  }
}
